### ISSUE TITLE
New version (0.2.3) crashes on startup

### ISSUE THREAD

**Issue by Tempest-5ky** [DrexHD/VanillaPermissions#15] opened 2024-02-10 19:31 UTC
What it says on the tin. Don't think it's actually a conflict with [Raknetify](https://modrinth.com/plugin/raknetify), more likely this mod's injection failure messed up the class that Raknetify was using, but you'll know more than me on the subject. This crash is present on both server and client after updating to the new version.

Error: https://mclo.gs/wYRuKVa
latest.log: https://mclo.gs/CL7FQbH

**Comment by DrexHD** [comment] 2024-02-10 23:15
I am unable to reproduce this, please try finding the incompatible mod (using binary search).
Also, why are you running this mod on the client? The main purpose is for it to be used server side.

**Comment by Tempest-5ky** [comment] 2024-02-11 01:06
Ack- my apologies, I'll do that! Will update this once I have.
Also, I'm running it on both server and client, as the mod page seemed to imply that having it on both was best?

**Comment by DrexHD** [comment] 2024-04-14 22:59
Bump!
You only need this mod on the server side for the majority of it's features. There is only one small QOL change for the client side: [client side](https://github.com/DrexHD/VanillaPermissions?tab=readme-ov-file#client-side)

**Comment by vocaloidkiss** [comment] 2024-04-23 19:19
it will make you stop at "load fabric permission"

**Comment by DrexHD** [comment] 2024-10-09 12:30
Closing this, because I can't reproduce. If anyone has anything helpful to share on this issue feel free to comment and I will reopen it.

**Closed by DrexHD** 2024-10-09 12:30 UTC

**Comment by vocaloidkiss** [comment] 2024-10-10 03:53
@DrexHD it is an error，sorry buddy，another mod cause the crash
