### ISSUE TITLE
java.lang.NoSuchMethodError | Whitelist error

### ISSUE THREAD

**Issue by LostAndDead** [DrexHD/VanillaPermissions#8] opened 2023-07-02 16:17 UTC
I am attempting to use this mod on a small **whitelisted** server I'm running with friends and whenever a player joins I get this error and the server crashes.

`java.lang.NoSuchMethodError: 'java.util.concurrent.CompletableFuture me.lucko.fabric.api.permissions.v0.Permissions.check(com.mojang.authlib.GameProfile, java.lang.String)'
at Not Enough Crashes deobfuscated stack trace.(1.19.2+build.28) ~[?:?]
at net.minecraft.server.dedicated.DedicatedPlayerManager.modifyReturnValue$ddn000$vanilla-permissions$vanillaPermissions_addBypassWhitelistPermission(DedicatedPlayerManager:1019) ~[?:?]
at net.minecraft.server.dedicated.DedicatedPlayerManager.isWhitelisted(DedicatedPlayerManager:124) ~[?:?]
at net.minecraft.server.PlayerManager.checkCanJoin(PlayerManager:423) ~[?:?]
at net.minecraft.server.network.ServerLoginNetworkHandler.acceptPlayer(ServerLoginNetworkHandler:122) ~[?:?]
at net.minecraft.server.network.ServerLoginNetworkHandler.redirect$bga000$fabric-networking-api-v1$handlePlayerJoin(ServerLoginNetworkHandler:563) ~[?:?]
at net.minecraft.server.network.ServerLoginNetworkHandler.tick(ServerLoginNetworkHandler:73) ~[?:?]
at net.minecraft.network.ClientConnection.tick(ClientConnection:248) ~[?:?]
at net.minecraft.server.ServerNetworkIo.tick(ServerNetworkIo:183) ~[?:?]
at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:886) ~[server-intermediary.jar:?]
at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer:289) ~[?:?]
at net.minecraft.server.MinecraftServer.tick(MinecraftServer:819) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:665) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:257) ~[server-intermediary.jar:?]
at java.lang.Thread.run(Thread.java:833) [?:?]`

It only crashes for other players, the reason it doesn't crash for me I think is that I joined and had my permissions set created as to say before I added this mod. I think the error originates from it trying to get permissions for a player who doesnt have any permissions made yet. I'm using luck perms to manage permissions as well as several other mods, but nothing that would impact permissions.

Game version is 1.19.2
Fabric version is 0.14.21
Im using the latest version of this mod
Server is running with java 17 openjdk

**Comment by DrexHD** [comment] 2023-07-10 10:11
Hey, sorry for the late response. This problem is likely caused by [fabric-permissions-api](https://github.com/lucko/fabric-permissions-api) (a library this mod uses), because multiple different versions of it are running on your server and the wrong (older) version gets picked by fabric-loader, because the dependency didn't properly increase it's version number.
Can you try adding [this file](https://file.io/SUvGbgkXS8R5) to your mods folder (it's the latest dependency version with a bumped version number)

**Comment by DrexHD** [comment] 2023-09-30 00:05
Fixed in the latest [1.20.2 release](https://github.com/DrexHD/VanillaPermissions/releases/tag/v0.2.2-1.20.2) (bumped fabric-permission-api version)

**Closed by DrexHD** 2023-09-30 00:05 UTC
